name: Generate Datas

on:
  schedule: # Execute a cada 12 horas
    - cron: "* */12 * * *"
  workflow_dispatch:  # Permite execução manual do workflow

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Snake Animation
      - uses: Platane/snk@v2.2.0  # Atualize para a última versão estável
        id: snake-gif
        with:
          github_user_name: leonardomiranda132  # Substitua pelo seu nome de usuário
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publicar a animação no GitHub Pages
      - name: Deploy Snake
        uses: crazy-max/ghaction-github-pages@v3  # Atualizado para v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
